swagger:
  outputDirectory: ./dist
  entryFile: 
    - ./src/controllers/*
  outputFormat: OpenApi_3
  host: localhost:7000
  name: CRUD Application
  description: A Sample application using Typescript-rest library
  license: MIT
  produces: [application/json]
  version: 0.0.1
  securityDefinitions:
    default:
      type: apiKey
      in: header
      name: Authorization
    secondAuthenticator:
      type: apiKey
      in: header
      name: Authorization
